#!/usr/bin/env python3
import sys
import subprocess

def run_pipeline(cmd):
    if "outputjson" in cmd:
        pipeline = f"{cmd} | jq -r '.generalDiagnostics[] | .file // .uri' | sort | uniq -c | sort -nr | head -n 1"
    elif "ruff" in cmd:
        pipeline = f"{cmd} | cut -d: -f1 | sort | uniq -c | sort -nr | head -n 1"
    
    subprocess.run(pipeline, shell=True)

if len(sys.argv) < 2:
    print("Usage: ./check_file {bp|p|r}")
    sys.exit(1)

mode = sys.argv[1]

commands = {
    "bp" : "uv run basedpyright --outputjson",
    "p"  : "pyright --outputjson",
    "r"  : "ruff check . --extend-exclude \".cache/*\" --quiet"
}

if mode in commands:
    run_pipeline(commands[mode])
else:
    print(f"Unknown mode: {mode}. Use bp, p, or r.")
